# Generated by Django 5.2 on 2025-06-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('can_manage_blog', 'Может управлять блогом')], 'verbose_name': 'Блоговая запись', 'verbose_name_plural': 'Блоговые записи'},
        ),
    ]
